Repository ledger/ledger, pull requests merged in 2023-12, with the labels that each got.

#2312 man: Fix common glyph usage errors
  doc/ledger.1
Labels: documentation, easy

#2291 Minor documentation update - on posting comments and fixed some examples
  doc/ledger3.texi
Labels: documentation

#2314 chore: Fix inline python format-strings
  contrib/non-profit-audit-reports/csv2ods.py
  test/LedgerHarness.py
Labels: easy

#2317 cmake: Minor clean-up regarding ICU version
  CMakeLists.txt
Labels: build, easy

#2316 test: Accept test names as arguments
  test/RegressTests.py
Labels: easy, tests

#2319 Fix compiler warning about std::binary_function being deprecated as of C++11
  src/CMakeLists.txt
  src/history.cc
  src/item.cc
Labels: easy
