Repository ledger/ledger, pull requests merged in 2023-03, with the labels that each got.

#2209 Re-add accidentially deleted PROJECT in CMakeLists.txt
  CMakeLists.txt
Labels: easy

#2218 flake: Run pre and post hooks in checkPhase
  flake.nix
Labels: easy

#2219 docs: Enable stand-alone building
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/LedgerVersion.cmake
Labels: easy

#2224 Change a use of is_realzero to just is_zero
  src/pool.cc
Labels: bug

#2225 Fix Python version check
  CMakeLists.txt
Labels: build, easy
