Repository ledger/ledger, pull requests merged in 2024-07, with the labels that each got.

#2289 print: Align amounts even when account names are long
  src/print.cc
  test/regress/align-amounts.test
Labels: enhancement

#2285 Use https scheme for links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, easy

#2367 Fix acprep script
  acprep
Labels: bug, build
